# $OpenBSD$

COMMENT =	encode/decode Perl utf-8 strings into TeX

DISTNAME =	TeX-Encode-2.006

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		textproc/p5-Pod-LaTeX>=0.56 \
			www/p5-HTML-Parser>=3.35

PKG_ARCH =		*

.include <bsd.port.mk>
