# $OpenBSD$

COMMENT =	Lexical Analyzer for Perl5

DISTNAME =	Compiler-Lexer-0.22

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

BUILD_DEPENDS =		devel/p5-Module-Build>=0.38 \
			devel/p5-Module-Build-XSUtil>=0.02

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
