# $OpenBSD$

COMMENT =	find a file within a set of paths like @INC or class paths

DISTNAME =	File-PathList-1.04

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Params-Util

CONFIGURE_STYLE =	modinst

MAKE_ENV +=	TEST_POD=Yes

PKG_ARCH =		*

.include <bsd.port.mk>
