# $OpenBSD$

COMMENT =	simplified interface to Log::Message

DISTNAME =	Log-Message-Simple-0.10

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Log-Message

PKG_ARCH =		*

.include <bsd.port.mk>
