# $OpenBSD$

COMMENT =	subtraction and intersection of character sets in Unicode

DISTNAME =	Unicode-Regex-Set-0.04

CATEGORIES =	converters

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

MAKE_ENV +=		TEST_POD=1

.include <bsd.port.mk>
