# $OpenBSD$

COMMENT =	teach ->new to accept single, non-hashref arguments

DISTNAME =	MooseX-OneArgNew-0.005

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose \
			devel/p5-MooseX-Role-Parameterized>=1.01 \
			devel/p5-namespace-autoclean
TEST_DEPENDS =		devel/p5-Moose

PKG_ARCH =		*

.include <bsd.port.mk>
