# $OpenBSD$

COMMENT =	subclass of Plack::Request which supports encoding

DISTNAME =	Plack-Request-WithEncoding-0.12

CATEGORIES =	www

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =	devel/p5-Hash-MultiValue \
                www/p5-Plack

TEST_DEPENDS =	www/p5-HTTP-Message

CONFIGURE_STYLE =	modbuild

PKG_ARCH =		*

.include <bsd.port.mk>
