# $OpenBSD$

COMMENT =	understanding configuration (cf) files for X12::Parser

DISTNAME =	X12-0.80

CATEGORIES =	cpan

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		cpan

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	PRASAD
.include <bsd.port.mk>
