# $OpenBSD$

COMMENT =	simple wrapper around Log::Dispatch

DISTNAME =	Log-Dispatchouli-2.019

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Log-Dispatch-Array \
			cpan/p5-String-Flogger \
			cpan/p5-Sub-Exporter-GlobExporter>=0.002 \
			devel/p5-Log-Dispatch \
			devel/p5-Params-Util \
			devel/p5-Sub-Exporter \
			devel/p5-Try-Tiny>=0.04
TEST_DEPENDS =		devel/p5-Test-Deep \
			devel/p5-Test-Fatal

PKG_ARCH =		*

.include <bsd.port.mk>
