# $OpenBSD$

COMMENT =	NativeTrait-like behavior for Moo

DISTNAME =	MooX-HandlesVia-0.001008

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Data-Perl>=0.002006 \
			devel/p5-Class-Method-Modifiers \
			devel/p5-Module-Runtime \
			devel/p5-Moo>=1.0030 \
			devel/p5-Role-Tiny
TEST_DEPENDS =		devel/p5-MooX-Types-MooseLike>=0.23 \
			devel/p5-Test-Exception \
			devel/p5-Test-Fatal

PKG_ARCH =		*

.include <bsd.port.mk>
