# $OpenBSD$

COMMENT =	Simple detection of binary versus text in strings

DISTNAME =	Data-Binary-0.01

CATEGORIES =	cpan

# Artistic 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
