# $OpenBSD$

COMMENT =	base classes wrapping fundamental Perl data types

DISTNAME =	Data-Perl-0.002009

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Class-Method-Modifiers \
			devel/p5-List-MoreUtils \
			devel/p5-Module-Runtime \
			devel/p5-Role-Tiny \
			devel/p5-strictures
TEST_DEPENDS =		devel/p5-Test-Deep \
			devel/p5-Test-Fatal \
			devel/p5-Test-Output

PKG_ARCH =		*

.include <bsd.port.mk>
