# $OpenBSD$

COMMENT =	Extract distribution name and version from a distribution

DISTNAME =	CPAN-DistnameInfo-0.12

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
