# $OpenBSD$

COMMENT =	export shared globs with Sub::Exporter collectors

DISTNAME =	Sub-Exporter-GlobExporter-0.005

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Sub-Exporter

PKG_ARCH =		*

.include <bsd.port.mk>
