# $OpenBSD$

COMMENT =	minimalist stored procedure mapper based on LedgerSMB

DISTNAME =	PGObject-Simple-3.000002

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-PGObject>=1.403.2

PKG_ARCH =		*

.include <bsd.port.mk>
