# $OpenBSD$

COMMENT =	toolkit integrating intelligent PostgreSQL dbs into Perl

DISTNAME =	PGObject-2.000002

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
