# $OpenBSD$

COMMENT =	XS functions to assist in parsing keyword syntax

DISTNAME =	XS-Parse-Keyword-0.21

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

BUILD_DEPENDS =	devel/p5-ExtUtils-CChecker>=0.11 \
		devel/p5-Module-Build>=0.4004

# Lines below not in the template
CPAN_AUTHOR =	PEVANS
.include <bsd.port.mk>
