# $OpenBSD$

COMMENT =	Subtraction and Intersection of Character Sets in Unicode

DISTNAME =	Unicode-Regex-Set-0.04

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
