# $OpenBSD$

COMMENT =	tool to scan your Perl code for its prerequisites

DISTNAME =	Perl-PrereqScanner-NotQuiteLite-0.9914

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
