# $OpenBSD$

COMMENT =	builds trie-ized regexp

DISTNAME =	Regexp-Trie-0.02

CATEGORIES =	cpan

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
