# $OpenBSD$

COMMENT =	MVP config reader for .ini files

DISTNAME =	Config-MVP-Reader-INI-2.101463

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Config-MVP>=2 \
			devel/p5-Config-IniFiles \
			devel/p5-Moose

PKG_ARCH =		*

.include <bsd.port.mk>
