# $OpenBSD$

COMMENT =	Test the Kwalitee of a distribution before you release it

DISTNAME =	Test-Kwalitee-1.28

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

# Lines below not in the template
FIX_EXTRACT_PERMISSIONS =	Yes
.include <bsd.port.mk>
