# $OpenBSD$

COMMENT =	tolerance ranges for inexact numbers

DISTNAME =	Number-Tolerant-1.708

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Sub-Exporter>=0.950

PKG_ARCH =		*

.include <bsd.port.mk>
