# $OpenBSD$

COMMENT =	Find a file within a set of paths (like @INC or Java

DISTNAME =	File-PathList-1.04

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Params-Util>=0.24

CONFIGURE_STYLE =	modinst

PKG_ARCH =		*

.include <bsd.port.mk>
