# $OpenBSD$

COMMENT =	DateTime Wrappers for PGObject

DISTNAME =	PGObject-Type-DateTime-2.000002

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-PGObject>=1.3 \
			devel/p5-DateTime>=1.05 \
			devel/p5-DateTime-TimeZone

PKG_ARCH =		*

.include <bsd.port.mk>
