# $OpenBSD$

COMMENT =	string munging for loggers

DISTNAME =	String-Flogger-1.101245

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		converters/p5-JSON-MaybeXS \
			devel/p5-Params-Util \
			devel/p5-Sub-Exporter

PKG_ARCH =		*

.include <bsd.port.mk>
