# $OpenBSD$

COMMENT =	PHP Mink inspired multi-protocol web-testing library for

DISTNAME =	Weasel-0.26

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-HTML-Selector-XPath \
			devel/p5-Module-Runtime \
			devel/p5-Moose \
			devel/p5-namespace-autoclean

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	EHUELS
.include <bsd.port.mk>
