# $OpenBSD$

COMMENT =	Timing side-channel protected string compare

DISTNAME =	String-Compare-ConstantTime-0.321

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

.include <bsd.port.mk>
