# $OpenBSD$

COMMENT =	count lines of code (cloc)

DISTNAME =	App-cloc-1.76

CATEGORIES =	cpan

# GPLv2
PERMIT_PACKAGE =	Yes

MODULES =		cpan

BUILD_DEPENDS =	devel/p5-Test-Compile>=1.2.1 \
		devel/p5-Test-Pod>=1.48
RUN_DEPENDS =		devel/p5-Algorithm-Diff>=1.1903 \
			devel/p5-Test-Compile>=1.2.1 \
			devel/p5-Test-Pod>=1.48 \
			textproc/p5-Regexp-Common>=201331301

PKG_ARCH =		*

.include <bsd.port.mk>
