# $OpenBSD$

COMMENT =	Math::BigFloat wrappers for PGObject classes

DISTNAME =	PGObject-Type-BigFloat-2.001

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-PGObject

PKG_ARCH =		*

.include <bsd.port.mk>
