# $OpenBSD$

COMMENT =	packages that provide templated software licenses

DISTNAME =	Software-License-0.103014

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Data-Section \
			textproc/p5-Text-Template
TEST_DEPENDS =		devel/p5-Try-Tiny

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	LEONT
.include <bsd.port.mk>
