# $OpenBSD$

COMMENT =	write-once, read-many attributes for Moose

DISTNAME =	MooseX-SetOnce-0.200002

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose>=0.90
TEST_DEPENDS =		devel/p5-Moose \
			devel/p5-Test-Fatal

PKG_ARCH =		*

.include <bsd.port.mk>
