# $OpenBSD$

COMMENT =	Declarative stored procedure <-> object mappings for the

DISTNAME =	PGObject-Util-DBMethod-1.01.000
PKGNAME =	p5-${DISTNAME:S/-v/-/}

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
