# $OpenBSD$

COMMENT =	declarative stored procedure <-> object mappings for the

DISTNAME =	PGObject-Util-DBMethod-1.00.003

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
