# $OpenBSD$

COMMENT =	Declare class attributes Moose-style

DISTNAME =	MooseX-ClassAttribute-0.29

CATEGORIES =	cpan

# Artistic 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose>=2.0 \
			devel/p5-namespace-autoclean>=0.11 \
			devel/p5-namespace-clean>=0.20
TEST_DEPENDS =		devel/p5-Test-Fatal \
			devel/p5-Test-Requires>=0.05

PKG_ARCH =		*

.include <bsd.port.mk>
