# $OpenBSD$

COMMENT =	parse and format ISO8601 duration

DISTNAME =	DateTime-Format-Duration-ISO8601-0.008

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-DateTime

TEST_DEPENDS =		devel/p5-Pod-Coverage-TrustPod \
			DateTime::Format::ISO8601::Format \
			devel/p5-Test-Perl-Critic \
			devel/p5-Test-Pod \
			devel/p5-Test-Pod-Coverage

PKG_ARCH =		*

.include <bsd.port.mk>

Test
DateTime::Format::ISO8601::Format


