# $OpenBSD$

COMMENT =	name your accessors get_foo() and set_foo()

DISTNAME =	MooseX-FollowPBP-0.05

CATEGORIES =	cpan

# Artistic 2.0
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose>=1.16

PKG_ARCH =		*

.include <bsd.port.mk>
