# $OpenBSD$

COMMENT =	Moose types that check against Perl syntax

DISTNAME =	MooseX-Types-Perl-0.101343

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-MooseX-Types \
			devel/p5-Params-Util

PKG_ARCH =		*

.include <bsd.port.mk>
