# $OpenBSD$

COMMENT =	get the full path to a locally installed module

DISTNAME =	Module-Path-0.19

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

TEST_DEPENDS =		cpan/p5-Devel-FindPerl

PKG_ARCH =		*

.include <bsd.port.mk>
