# $OpenBSD$

COMMENT =	thing with a list of tags

DISTNAME =	Role-Identifiable-0.007

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Moose
TEST_DEPENDS =		${RUN_DEPENDS}

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	RJBS
.include <bsd.port.mk>
