# $OpenBSD$

COMMENT =	comprehensive template processing system

DISTNAME =	Template-Toolkit-3.009

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

RUN_DEPENDS =		devel/p5-AppConfig>=1.56
TEST_DEPENDS =		devel/p5-Test-LeakTrace \
			www/p5-CGI>=4.11

.include <bsd.port.mk>
