# $OpenBSD$

COMMENT =	create a new file in the Excel 2007+ XLSX format

DISTNAME =	Excel-Writer-XLSX-1.01

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		archivers/p5-Archive-Zip>=1.3

PKG_ARCH =		*

.include <bsd.port.mk>
