# $OpenBSD$

COMMENT =	Parse cpanfile

DISTNAME =	Module-CPANfile-1.1004

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

TEST_DEPENDS =		devel/p5-File-pushd

PKG_ARCH =		*

.include <bsd.port.mk>
