# $OpenBSD$

COMMENT =	extremely fast HTML escaping

DISTNAME =	HTML-Escape-1.10

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

WANTLIB =		perl

MODULES =		cpan

BUILD_DEPENDS =		cpan/p5-Module-Build-Pluggable-PPPort>=0.04 \
			devel/p5-Module-Build>=0.4005 \
			devel/p5-Test-Requires

CONFIGURE_STYLE =	modbuild

.include <bsd.port.mk>
