# $OpenBSD$

COMMENT =	thing with a message method

DISTNAME =	Role-HasMessage-0.006

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-String-Errf \
			devel/p5-Moose \
			devel/p5-MooseX-Role-Parameterized \
			devel/p5-Try-Tiny \
			devel/p5-namespace-clean
TEST_DEPENDS =		devel/p5-Moose

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	RJBS
.include <bsd.port.mk>
