# $OpenBSD$

COMMENT =	log events to an array (reference)

DISTNAME =	Log-Dispatch-Array-1.003

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Log-Dispatch
TEST_DEPENDS =		devel/p5-Test-Deep

PKG_ARCH =		*

.include <bsd.port.mk>
