# $OpenBSD$

COMMENT =	allow a module's pod to contain Pod::Coverage hints

DISTNAME =	Pod-Coverage-TrustPod-0.100005

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Pod-Eventual \
			devel/p5-Pod-Coverage \
			textproc/p5-Pod-Parser

PKG_ARCH =		*

.include <bsd.port.mk>
