# $OpenBSD$

COMMENT =	make try/catch syntax available

DISTNAME =	Feature-Compat-Try-0.04

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

# Lines below not in the template
CPAN_AUTHOR =	PEVANS
.include <bsd.port.mk>
