# $OpenBSD$

COMMENT =	user interfaces via Term::ReadLine made easy

DISTNAME =	Term-UI-0.46

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Log-Message-Simple

PKG_ARCH =		*

.include <bsd.port.mk>
