# $OpenBSD$

COMMENT =	Minimalist stored procedure mapper based on LedgerSMB's

DISTNAME =	PGObject-Simple-3.1.0
PKGNAME =	p5-${DISTNAME:S/-v/-/}

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-PGObject>=1.403.2 \
			devel/p5-Carp-Clan \
			devel/p5-Log-Any

PKG_ARCH =		*

.include <bsd.port.mk>
