# $OpenBSD$

COMMENT =	declare class attributes Moose-style... but without Moose

DISTNAME =	MooX-ClassAttribute-0.011

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Exporter-Tiny \
			devel/p5-Moo>=1.0 \
			devel/p5-Role-Tiny>=1.0

PKG_ARCH =		*

.include <bsd.port.mk>
