# $OpenBSD$

COMMENT =	Moo/Moose mappers for minimalist PGObject framework

DISTNAME =	PGObject-Simple-Role-2.1.1
PKGNAME =	p5-${DISTNAME:S/-v/-/}

CATEGORIES =	cpan

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-PGObject-Simple>=3 \
			devel/p5-Carp-Clan \
			devel/p5-Log-Any \
			devel/p5-Moo

PKG_ARCH =		*

.include <bsd.port.mk>
