# $OpenBSD: Makefile.template,v 1.85 2019/09/09 19:19:05 kmos Exp $

COMMENT =		define range of numbers and test if number is in the range

DISTNAME =		Number-Range-0.12

CATEGORIES =		math

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

MAKE_ENV=		TEST_POD=Yes

PKG_ARCH =		*

.include <bsd.port.mk>
