# $OpenBSD$

COMMENT =	Weasel extension set testing Dojo-based web apps (tag

DISTNAME =	Weasel-Widgets-Dojo-0.05

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Weasel>=0.23 \
			devel/p5-Moose
TEST_DEPENDS =		devel/p5-Perl-Critic

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	EHUELS
.include <bsd.port.mk>
