# $OpenBSD$

COMMENT =	C implementation of the ISAAC PRNG algorithm

DISTNAME =	Math-Random-ISAAC-XS-1.004

CATEGORIES =	cpan

# unknown license -> 'unrestricted'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

WANTLIB =		perl

MODULES =		cpan

BUILD_DEPENDS =	devel/p5-Module-Build>=0.2808_01 \
		devel/p5-Test-NoWarnings>=0.084

CONFIGURE_STYLE =	modbuild

# Lines below not in the template
FIX_EXTRACT_PERMISSIONS =	Yes
.include <bsd.port.mk>
