# $OpenBSD$

COMMENT =	simple sprintf-like dialect

DISTNAME =	String-Errf-0.008

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

RUN_DEPENDS =		devel/p5-Params-Util \
			devel/p5-String-Formatter>=0.102081 \
			devel/p5-Sub-Exporter
TEST_DEPENDS =		converters/p5-JSON-MaybeXS \
			devel/p5-Time-TimeDate

PKG_ARCH =		*

.include <bsd.port.mk>
