# $OpenBSD$

COMMENT =	compare version strings

DISTNAME =	Version-Compare-0.14

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

# Lines below not in the template
CPAN_AUTHOR =	TEX
.include <bsd.port.mk>
