# $OpenBSD$

COMMENT =	Powerful and flexible message logging mechanism

DISTNAME =	Log-Message-0.08

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
