# $OpenBSD$

COMMENT =	Perl extension defining ranges of numbers and testing if a

DISTNAME =	Number-Range-0.12

CATEGORIES =	cpan

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		cpan

PKG_ARCH =		*

.include <bsd.port.mk>
