# $OpenBSD$

COMMENT =	Latex support for the Template Toolkit

DISTNAME =	Template-Plugin-Latex-3.12

CATEGORIES =	cpan

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-LaTeX-Table \
			textproc/p5-LaTeX-Driver>=0.07 \
			textproc/p5-LaTeX-Encode>=0.02 \
			textproc/p5-Template>=2.16

PKG_ARCH =		*

.include <bsd.port.mk>
