# $OpenBSD$

COMMENT =	CSS Selector to XPath compiler

DISTNAME =	HTML-Selector-XPath-0.25

CATEGORIES =	cpan

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

TEST_DEPENDS =		devel/p5-Test-Base

CONFIGURE_STYLE =	perl modinst

PKG_ARCH =		*

.include <bsd.port.mk>
